/*
 * History - browse how the classification of roles, role actions and API
 * permissions changed over time. Three ways to look at it:
 *
 *   - Timeline : every recorded update (a point in time), with what was added,
 *                removed or re-tiered compared to the previous version. No commit
 *                messages or hashes - just dates and an easy-to-follow change list.
 *   - Compare  : pick any two dates and see the net difference between them.
 *   - Find     : type a role, role action or permission name to see its own
 *                change timeline across the whole history (this is what the
 *                "View change history" links elsewhere in the app open).
 *
 * Data: window.EOCE_HISTORY (generated by Update-EntraOpsClassificationExplorerData -Mode Standalone from
 * `git log`). Entirely client-side: the view degrades to an empty state when the
 * bundle is absent. Per-commit diffs are folded into cumulative snapshots so any
 * two dates can be compared without needing the raw git history at runtime.
 */
window.EOCE = window.EOCE || {};
EOCE.views = EOCE.views || {};

EOCE.views.history = {
    state: { source: null, sha: null, q: '', mode: 'timeline', fromSha: null, toSha: null },

    esc: function (s) { return EOCE.util.escapeHtml(s); },

    fmtDate: function (iso) {
        try {
            var d = new Date(iso);
            if (isNaN(d.getTime())) return String(iso);
            return d.toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' });
        } catch (e) { return String(iso); }
    },

    data: function () { return window.EOCE_HISTORY; },

    sourceKeys: function () {
        var d = this.data();
        return d && d.sources ? Object.keys(d.sources) : [];
    },

    source: function (key) {
        var d = this.data();
        return d && d.sources ? d.sources[key] : null;
    },

    // --- Cumulative snapshots (for date comparison) -----------------------
    // Fold the per-commit diffs into a full state after each commit, so any
    // commit's snapshot can be diffed against any other. Cached per source key.
    _snapCache: {},
    snapshots: function (sourceKey) {
        if (this._snapCache[sourceKey]) return this._snapCache[sourceKey];
        var src = this.source(sourceKey);
        var commits = (src && src.commits) || [];
        var kind = src && src.kind;
        var state = {};
        var snaps = [];
        commits.forEach(function (c) {
            (c.added || []).forEach(function (it) {
                if (kind === 'permissions') {
                    state[it.id] = { name: it.name, tier: it.tier, category: it.category };
                } else {
                    var acts = {};
                    (it.actions || []).forEach(function (a) { acts[a] = true; });
                    state[it.id] = { name: it.name, tier: it.tier, actions: acts };
                }
            });
            (c.changed || []).forEach(function (it) {
                var e = state[it.id];
                if (!e) { e = (kind === 'permissions') ? { actions: undefined } : { actions: {} }; state[it.id] = e; }
                e.name = it.name;
                e.tier = it.newTier;
                if (kind === 'permissions') {
                    if (it.newCategory !== undefined) e.category = it.newCategory;
                } else {
                    e.actions = e.actions || {};
                    (it.actionsRemoved || []).forEach(function (a) { delete e.actions[a]; });
                    (it.actionsAdded || []).forEach(function (a) { e.actions[a] = true; });
                }
            });
            (c.removed || []).forEach(function (it) { delete state[it.id]; });
            // Deep-ish copy so each snapshot is independent of later mutation.
            var copy = {};
            Object.keys(state).forEach(function (id) {
                var e = state[id];
                if (kind === 'permissions') copy[id] = { name: e.name, tier: e.tier, category: e.category };
                else {
                    var a = {}; Object.keys(e.actions || {}).forEach(function (k) { a[k] = true; });
                    copy[id] = { name: e.name, tier: e.tier, actions: a };
                }
            });
            snaps.push(copy);
        });
        this._snapCache[sourceKey] = snaps;
        return snaps;
    },

    commitIndexBySha: function (sourceKey, sha) {
        var src = this.source(sourceKey);
        var commits = (src && src.commits) || [];
        for (var i = 0; i < commits.length; i++) { if (commits[i].sha === sha) return i; }
        return -1;
    },

    // Diff two snapshots (from snapshots()) into the same {added,removed,changed}
    // shape as a per-commit diff, so the shared change-list renderer can be reused.
    diffSnapshots: function (prev, curr, kind) {
        prev = prev || {}; curr = curr || {};
        var added = [], removed = [], changed = [];
        Object.keys(curr).forEach(function (id) {
            var c = curr[id];
            if (!prev[id]) { added.push({ id: id, name: c.name, tier: c.tier }); return; }
            var p = prev[id];
            if (kind === 'permissions') {
                if (p.tier !== c.tier || p.category !== c.category) {
                    changed.push({ id: id, name: c.name, oldTier: p.tier, newTier: c.tier, oldCategory: p.category, newCategory: c.category });
                }
            } else {
                var addedActs = [], removedActs = [];
                Object.keys(c.actions || {}).forEach(function (a) { if (!(p.actions || {})[a]) addedActs.push(a); });
                Object.keys(p.actions || {}).forEach(function (a) { if (!(c.actions || {})[a]) removedActs.push(a); });
                if (p.tier !== c.tier || addedActs.length || removedActs.length) {
                    changed.push({ id: id, name: c.name, oldTier: p.tier, newTier: c.tier, actionsAdded: addedActs.sort(), actionsRemoved: removedActs.sort() });
                }
            }
        });
        Object.keys(prev).forEach(function (id) {
            if (!curr[id]) { var p = prev[id]; removed.push({ id: id, name: p.name, tier: p.tier }); }
        });
        function byName(a, b) { return String(a.name || '').toLowerCase() < String(b.name || '').toLowerCase() ? -1 : 1; }
        return { added: added.sort(byName), removed: removed.sort(byName), changed: changed.sort(byName) };
    },

    render: function (el, params) {
        if (!window.EOCE_HISTORY) {
            var self = this;
            return EOCE.util.ensureHistory().then(function () { return self.render(el, params); });
        }
        var d = this.data();
        var keys = this.sourceKeys();

        if (!d || !keys.length) {
            el.innerHTML =
                '<div class="view">' +
                '<div class="page-head"><h1>History</h1>' +
                '<p>See how the classification of roles, role actions and API permissions changed over time.</p></div>' +
                '<div class="empty" style="padding:48px;"><div class="big">&#9202;</div>' +
                'No change history is embedded in this copy of the app.<br><br>' +
                'Run <span class="cell-mono">' + this.esc(EOCE.GENERATOR_COMMAND) + '</span> from a full git clone of the repository ' +
                '(not a downloaded zip) to generate <span class="cell-mono">data/history-data.js</span>, then reload.</div>' +
                '</div>';
            return;
        }

        if (params && params[0] && d.sources[params[0]]) this.state.source = params[0];
        if (!this.state.source || !d.sources[this.state.source]) this.state.source = keys[0];
        // Deep links: #history/<src>/find/<name> opens the per-item timeline;
        // #history/<src>/<sha> selects a point in time.
        if (params && params[1] === 'find' && params[2]) { this.state.q = params[2]; this.state.mode = 'timeline'; }
        else if (params && params[1]) { this.state.sha = params[1]; this.state.q = ''; }

        el.innerHTML =
            '<div class="view">' +
            '<div class="page-head"><h1>History</h1>' +
            '<p>How the classification of roles, role actions and API permissions changed over time. Pick a date on the timeline to see what changed, compare any two dates, or search a name to follow its own change history.</p></div>' +
            '<div id="histToolbar"></div>' +
            '<div class="hist-layout">' +
            '<div class="hist-timeline" id="histTimeline"></div>' +
            '<div class="hist-detail" id="histDetail"></div>' +
            '</div>' +
            '</div>';

        this.renderToolbar();
        this.renderTimeline();
        this.renderDetail();
    },

    renderToolbar: function () {
        var self = this;
        var keys = this.sourceKeys();
        var html = '<div class="toolbar">';
        html += '<div class="seg-group" id="histSourceSeg">';
        keys.forEach(function (k) {
            var src = self.source(k);
            html += '<button class="seg' + (self.state.source === k ? ' active' : '') + '" data-src="' + k + '">' +
                self.esc(src.label) + ' <span class="muted">(' + EOCE.util.formatNumber(src.commitCount) + ')</span></button>';
        });
        html += '</div>';
        html += '<div class="seg-group" id="histModeSeg">' +
            '<button class="seg' + (this.state.mode === 'timeline' ? ' active' : '') + '" data-mode="timeline">Timeline</button>' +
            '<button class="seg' + (this.state.mode === 'compare' ? ' active' : '') + '" data-mode="compare">Compare dates</button>' +
            '</div>';
        html += '<div class="search"><span class="search-ico">&#128269;</span>' +
            '<input id="histSearch" type="text" placeholder="Find a role, role action or permission&hellip;" value="' + this.esc(this.state.q) + '"></div>';
        html += '</div>';
        document.getElementById('histToolbar').innerHTML = html;

        document.getElementById('histSourceSeg').addEventListener('click', function (e) {
            var b = e.target.closest('[data-src]'); if (!b) return;
            self.state.source = b.getAttribute('data-src');
            self.state.sha = null;
            self.state.q = '';
            self.state.fromSha = null;
            self.state.toSha = null;
            self.renderToolbar();
            self.renderTimeline();
            self.renderDetail();
        });
        document.getElementById('histModeSeg').addEventListener('click', function (e) {
            var b = e.target.closest('[data-mode]'); if (!b) return;
            self.state.mode = b.getAttribute('data-mode');
            self.state.q = '';
            var si = document.getElementById('histSearch'); if (si) si.value = '';
            self.renderToolbar();
            self.renderTimeline();
            self.renderDetail();
        });
        document.getElementById('histSearch').addEventListener('input', EOCE.util.debounce(function (e) {
            self.state.q = e.target.value.trim();
            self.renderTimeline();
            self.renderDetail();
        }, 180));
    },

    tierArrow: function (oldTier, newTier) {
        if (!oldTier || oldTier === newTier) return EOCE.util.tierBadge(newTier, { short: true });
        return '<span class="hist-tier-arrow">' + EOCE.util.tierBadge(oldTier, { short: true }) + '<span class="muted">&rarr;</span>' + EOCE.util.tierBadge(newTier, { short: true }) + '</span>';
    },

    renderTimeline: function () {
        var self = this;
        var src = this.source(this.state.source);
        var host = document.getElementById('histTimeline');
        if (!host) return;
        var commits = (src && src.commits) || [];

        if (!commits.length) {
            host.innerHTML = '<div class="empty" style="padding:24px;">No history recorded for this source.</div>';
            return;
        }

        // Compare mode: the sidebar becomes the From / To date pickers.
        if (this.state.mode === 'compare') {
            if (!this.state.fromSha) this.state.fromSha = commits[0].sha;
            if (!this.state.toSha) this.state.toSha = commits[commits.length - 1].sha;
            var opts = function (selSha) {
                return commits.map(function (c) {
                    return '<option value="' + c.sha + '"' + (c.sha === selSha ? ' selected' : '') + '>' + self.esc(self.fmtDate(c.date)) + '</option>';
                }).join('');
            };
            host.innerHTML =
                '<div class="hist-compare-picker">' +
                '<div class="hist-compare-title">Compare two dates</div>' +
                '<label class="hist-compare-field"><span>From</span>' +
                '<select id="histFrom" class="filter">' + opts(this.state.fromSha) + '</select></label>' +
                '<label class="hist-compare-field"><span>To</span>' +
                '<select id="histTo" class="filter">' + opts(this.state.toSha) + '</select></label>' +
                '<p class="muted" style="font-size:12px;margin:10px 2px 0;">Shows the net difference between the two selected points in time.</p>' +
                '</div>';
            document.getElementById('histFrom').addEventListener('change', function (e) { self.state.fromSha = e.target.value; self.renderDetail(); });
            document.getElementById('histTo').addEventListener('change', function (e) { self.state.toSha = e.target.value; self.renderDetail(); });
            return;
        }

        if (!this.state.sha) this.state.sha = commits[commits.length - 1].sha;

        var html = '';
        commits.slice().reverse().forEach(function (c) {
            var active = c.sha === self.state.sha;
            var dateStr = self.fmtDate(c.date);
            html += '<div class="hist-commit' + (active ? ' active' : '') + '" data-sha="' + c.sha + '">' +
                '<div class="hist-commit-head"><span class="hist-commit-date">' + self.esc(dateStr) + '</span></div>' +
                '<div class="hist-commit-chips">' +
                (c.added.length ? '<span class="chip diff-add">+' + EOCE.util.formatNumber(c.added.length) + ' new</span>' : '') +
                (c.removed.length ? '<span class="chip diff-del">&minus;' + EOCE.util.formatNumber(c.removed.length) + ' removed</span>' : '') +
                (c.changed.length ? '<span class="chip diff-move">~' + EOCE.util.formatNumber(c.changed.length) + ' changed</span>' : '') +
                '</div></div>';
        });
        host.innerHTML = html;

        host.querySelectorAll('.hist-commit[data-sha]').forEach(function (node) {
            node.addEventListener('click', function () {
                self.state.sha = node.getAttribute('data-sha');
                self.state.q = '';
                var si = document.getElementById('histSearch');
                if (si) si.value = '';
                self.renderTimeline();
                self.renderDetail();
            });
        });
    },

    // Shared renderer for an added / removed / changed change list (used by the
    // per-date detail and the compare-dates detail). No commit message or hash.
    changeListHtml: function (diff, kind) {
        var self = this;
        var LIMIT = 200;
        var html = '';

        function itemRow(it) {
            return '<div class="hist-item-row"><span class="hist-item-name">' + EOCE.util.escapeHtml(it.name) + '</span>' +
                EOCE.util.tierBadge(it.tier, { short: true }) + '</div>';
        }

        if (diff.added.length) {
            html += '<div class="section-title"><span class="chip diff-add">+ added</span> ' + EOCE.util.formatNumber(diff.added.length) + '</div>';
            diff.added.slice(0, LIMIT).forEach(function (it) { html += itemRow(it); });
            if (diff.added.length > LIMIT) html += '<div class="muted" style="padding:6px 4px;">&hellip; and ' + EOCE.util.formatNumber(diff.added.length - LIMIT) + ' more</div>';
        }
        if (diff.removed.length) {
            html += '<div class="section-title"><span class="chip diff-del">&minus; removed</span> ' + EOCE.util.formatNumber(diff.removed.length) + '</div>';
            diff.removed.slice(0, LIMIT).forEach(function (it) { html += itemRow(it); });
            if (diff.removed.length > LIMIT) html += '<div class="muted" style="padding:6px 4px;">&hellip; and ' + EOCE.util.formatNumber(diff.removed.length - LIMIT) + ' more</div>';
        }
        if (diff.changed.length) {
            html += '<div class="section-title"><span class="chip diff-move">~ changed</span> ' + EOCE.util.formatNumber(diff.changed.length) + '</div>';
            diff.changed.slice(0, LIMIT).forEach(function (it) {
                html += '<div class="hist-item-row" style="align-items:flex-start;flex-direction:column;gap:4px;">' +
                    '<div style="display:flex;align-items:center;gap:8px;width:100%;">' +
                    '<span class="hist-item-name">' + EOCE.util.escapeHtml(it.name) + '</span>' +
                    self.tierArrow(it.oldTier, it.newTier) +
                    '</div>';
                if (kind === 'permissions') {
                    if (it.oldCategory !== it.newCategory) {
                        html += '<div class="hist-item-sub">Category: ' + EOCE.util.escapeHtml(it.oldCategory || '—') + ' &rarr; ' + EOCE.util.escapeHtml(it.newCategory || '—') + '</div>';
                    }
                } else {
                    if (it.actionsAdded && it.actionsAdded.length) {
                        html += '<div class="hist-item-sub"><span class="chip diff-add" style="font-size:10.5px;">+' + it.actionsAdded.length + ' action' + (it.actionsAdded.length === 1 ? '' : 's') + '</span> ' +
                            EOCE.util.escapeHtml(it.actionsAdded.slice(0, 6).join(', ')) + (it.actionsAdded.length > 6 ? '…' : '') + '</div>';
                    }
                    if (it.actionsRemoved && it.actionsRemoved.length) {
                        html += '<div class="hist-item-sub"><span class="chip diff-del" style="font-size:10.5px;">&minus;' + it.actionsRemoved.length + ' action' + (it.actionsRemoved.length === 1 ? '' : 's') + '</span> ' +
                            EOCE.util.escapeHtml(it.actionsRemoved.slice(0, 6).join(', ')) + (it.actionsRemoved.length > 6 ? '…' : '') + '</div>';
                    }
                }
                html += '</div>';
            });
            if (diff.changed.length > LIMIT) html += '<div class="muted" style="padding:6px 4px;">&hellip; and ' + EOCE.util.formatNumber(diff.changed.length - LIMIT) + ' more</div>';
        }
        return html;
    },

    // Short "3 added · 1 removed · 2 changed" summary line for a diff.
    summaryLine: function (diff) {
        var parts = [];
        if (diff.added.length) parts.push(EOCE.util.formatNumber(diff.added.length) + ' added');
        if (diff.removed.length) parts.push(EOCE.util.formatNumber(diff.removed.length) + ' removed');
        if (diff.changed.length) parts.push(EOCE.util.formatNumber(diff.changed.length) + ' changed');
        return parts.length ? parts.join(' · ') : 'no changes';
    },

    renderDetail: function () {
        var host = document.getElementById('histDetail');
        if (!host) return;
        if (this.state.mode === 'compare') { this.renderCompareDetail(host); return; }
        if (this.state.q) { this.renderSearchDetail(host); return; }
        this.renderCommitDetail(host);
    },

    // A single point in time: what changed compared to the previous version.
    renderCommitDetail: function (host) {
        var src = this.source(this.state.source);
        var commits = (src && src.commits) || [];
        var c = commits.filter(function (x) { return x.sha === this.state.sha; }, this)[0] || commits[commits.length - 1];
        if (!c) { host.innerHTML = '<div class="empty" style="padding:24px;">Select a date on the timeline to see what changed.</div>'; return; }

        var diff = { added: c.added, removed: c.removed, changed: c.changed };
        var html = '<div class="hist-detail-head">' +
            '<span class="cell-strong" style="font-size:15px;">' + this.esc(this.fmtDate(c.date)) + '</span>' +
            '<span class="muted">' + this.esc(this.summaryLine(diff)) + '</span>' +
            '</div>';

        if (!c.added.length && !c.removed.length && !c.changed.length) {
            html += '<div class="empty" style="padding:20px;">No change recorded at this point.</div>';
            host.innerHTML = html;
            return;
        }
        html += this.changeListHtml(diff, src.kind);
        host.innerHTML = html;
    },

    // Net difference between two chosen dates.
    renderCompareDetail: function (host) {
        var src = this.source(this.state.source);
        var commits = (src && src.commits) || [];
        if (!commits.length) { host.innerHTML = '<div class="empty" style="padding:24px;">No history recorded for this source.</div>'; return; }

        var snaps = this.snapshots(this.state.source);
        var fromIdx = this.commitIndexBySha(this.state.source, this.state.fromSha);
        var toIdx = this.commitIndexBySha(this.state.source, this.state.toSha);
        if (fromIdx === -1) fromIdx = 0;
        if (toIdx === -1) toIdx = commits.length - 1;

        // Order the pair chronologically so "From" is always the earlier snapshot.
        var lo = Math.min(fromIdx, toIdx), hi = Math.max(fromIdx, toIdx);
        var fromDate = this.fmtDate(commits[lo].date);
        var toDate = this.fmtDate(commits[hi].date);

        if (lo === hi) {
            host.innerHTML = '<div class="hist-detail-head"><span class="cell-strong" style="font-size:15px;">' +
                this.esc(fromDate) + '</span></div>' +
                '<div class="empty" style="padding:20px;">Pick two different dates to compare.</div>';
            return;
        }

        var diff = this.diffSnapshots(snaps[lo], snaps[hi], src.kind);
        var html = '<div class="hist-detail-head">' +
            '<span class="cell-strong" style="font-size:15px;">' + this.esc(fromDate) + ' <span class="muted">&rarr;</span> ' + this.esc(toDate) + '</span>' +
            '<span class="muted">' + this.esc(this.summaryLine(diff)) + '</span>' +
            '</div>';

        if (!diff.added.length && !diff.removed.length && !diff.changed.length) {
            html += '<div class="empty" style="padding:20px;">Nothing changed between these two dates.</div>';
            host.innerHTML = html;
            return;
        }
        html += this.changeListHtml(diff, src.kind);
        host.innerHTML = html;
    },

    // Cross-time timeline for a single item name (role, role action, or permission)
    // matched case-insensitively against every added/removed/changed entry recorded
    // for the active source - including role actions nested inside a role's own
    // record. No commit message or hash: each entry is just a date and a plain-language
    // description of what happened.
    renderSearchDetail: function (host) {
        var self = this;
        var src = this.source(this.state.source);
        var commits = (src && src.commits) || [];
        var kind = src.kind;
        var q = this.state.q.toLowerCase();

        var hits = [];
        commits.forEach(function (c) {
            ['added', 'removed', 'changed'].forEach(function (bucket) {
                (c[bucket] || []).forEach(function (it) {
                    if (String(it.name || '').toLowerCase().indexOf(q) !== -1) {
                        hits.push({ commit: c, bucket: bucket, type: 'item', item: it });
                    }
                    if (kind === 'permissions') return;
                    var addedActs = bucket === 'changed' ? (it.actionsAdded || []) : (bucket === 'added' ? (it.actions || []) : []);
                    var removedActs = bucket === 'changed' ? (it.actionsRemoved || []) : (bucket === 'removed' ? (it.actions || []) : []);
                    addedActs.forEach(function (a) {
                        if (a.toLowerCase().indexOf(q) === -1) return;
                        hits.push({ commit: c, type: 'action', status: 'added', action: a, roleName: it.name, viaWholeRole: bucket === 'added' });
                    });
                    removedActs.forEach(function (a) {
                        if (a.toLowerCase().indexOf(q) === -1) return;
                        hits.push({ commit: c, type: 'action', status: 'removed', action: a, roleName: it.name, viaWholeRole: bucket === 'removed' });
                    });
                });
            });
        });

        var html = '<div class="hist-detail-head"><span class="cell-strong" style="font-size:15px;">Change history for &ldquo;' + this.esc(this.state.q) + '&rdquo;</span>' +
            '<span class="muted">' + EOCE.util.formatNumber(hits.length) + ' change' + (hits.length === 1 ? '' : 's') + ' in ' + this.esc(src.label) + '</span></div>';

        if (!hits.length) {
            html += '<div class="empty" style="padding:20px;">No matching role, role action or permission was added, removed or changed in this source’s recorded history.</div>';
            host.innerHTML = html;
            return;
        }

        html += '<div class="hist-track">';
        hits.slice().reverse().slice(0, 100).forEach(function (h) {
            var dateStr = self.fmtDate(h.commit.date);
            if (h.type === 'action') {
                var actionChip = h.status === 'added' ? '<span class="chip diff-add">+ added</span>' : '<span class="chip diff-del">&minus; removed</span>';
                var viaNote = h.viaWholeRole
                    ? (h.status === 'added' ? 'introduced with new role' : 'removed with role')
                    : (h.status === 'added' ? 'added to role' : 'removed from role');
                html += '<div class="hist-track-item">' +
                    '<div class="hist-track-date">' + self.esc(dateStr) + '</div>' +
                    '<div class="hist-track-body">' +
                    '<div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap;">' + actionChip +
                    '<span class="cell-strong cell-mono" style="font-size:12.5px;">' + EOCE.util.escapeHtml(h.action) + '</span>' +
                    '</div>' +
                    '<div class="hist-item-sub">' + self.esc(viaNote) + ' <strong>' + EOCE.util.escapeHtml(h.roleName) + '</strong></div>' +
                    '</div></div>';
                return;
            }
            var bucketChip = h.bucket === 'added' ? '<span class="chip diff-add">+ added</span>' :
                h.bucket === 'removed' ? '<span class="chip diff-del">&minus; removed</span>' :
                    '<span class="chip diff-move">~ changed</span>';
            var sub = '';
            if (h.bucket === 'changed') {
                if (kind === 'permissions') {
                    if (h.item.oldCategory !== h.item.newCategory) sub = 'Category: ' + self.esc(h.item.oldCategory || '—') + ' → ' + self.esc(h.item.newCategory || '—');
                } else {
                    var bits = [];
                    if (h.item.actionsAdded && h.item.actionsAdded.length) bits.push('+' + h.item.actionsAdded.length + ' action' + (h.item.actionsAdded.length === 1 ? '' : 's'));
                    if (h.item.actionsRemoved && h.item.actionsRemoved.length) bits.push('−' + h.item.actionsRemoved.length + ' action' + (h.item.actionsRemoved.length === 1 ? '' : 's'));
                    sub = bits.join(' · ');
                }
            }
            html += '<div class="hist-track-item">' +
                '<div class="hist-track-date">' + self.esc(dateStr) + '</div>' +
                '<div class="hist-track-body">' +
                '<div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap;">' + bucketChip +
                '<span class="cell-strong">' + EOCE.util.escapeHtml(h.item.name) + '</span>' +
                (h.bucket === 'changed' ? self.tierArrow(h.item.oldTier, h.item.newTier) : EOCE.util.tierBadge(h.item.tier, { short: true })) +
                '</div>' +
                (sub ? '<div class="hist-item-sub">' + sub + '</div>' : '') +
                '</div></div>';
        });
        html += '</div>';
        if (hits.length > 100) html += '<div class="muted" style="padding:6px 4px;">Showing the 100 most recent changes.</div>';

        host.innerHTML = html;
    }
};
