/*
 * Overview (Enterprise Access Model Map) - Sankey visualization of the classification model.
 *
 * Flow:  Role system -> Role -> Service -> Role action -> Tier level
 *
 * Adopts the approach of the "Privileged Tiering Sankey"
 * (Reporting_EntraOpsTierBreach) but is driven by the EntraOps classification
 * output (the bundled Classification_*.json files) instead of assignment data.
 * It surfaces which roles and role actions land in which Enterprise Access Model
 * tier (notably Control Plane) and why - the actions that pull a role up to the
 * highest-privilege plane.
 *
 * Data: window.EOCE_TIER_MAP (generated by Update-EntraOpsClassificationExplorerData) when
 * present, otherwise derived client-side from the embedded classification bundle.
 */
window.EOCE = window.EOCE || {};
EOCE.views = EOCE.views || {};

EOCE.views.tiermap = {
    // Left -> right column catalog. Each column knows how to derive a node id,
    // a display name, a tier (for colouring) and the node "kind".
    COLUMNS: {
        system: {
            label: 'Role system', kind: 'system',
            id: function (p) { return 'SY:' + p.sys; },
            name: function (p) { return (EOCE.RBAC_SYSTEMS[p.sys] || {}).short || p.sys; },
            tier: function () { return null; }
        },
        role: {
            label: 'Role', kind: 'role',
            id: function (p) { return 'R:' + p.sys + '|' + p.roleId; },
            name: function (p) { return p.role; },
            tier: function (p) { return p.roleClass; },
            meta: function (p) { return (EOCE.RBAC_SYSTEMS[p.sys] || {}).short || p.sys; }
        },
        service: {
            label: 'Service', kind: 'service',
            id: function (p) { return 'SV:' + p.sys + '|' + p.service; },
            name: function (p) { return p.service; },
            tier: function () { return null; }
        },
        action: {
            label: 'Role action', kind: 'action',
            id: function (p) { return 'A:' + p.sys + '|' + (p.actionType === 'DataAction' ? 'DataAction' : 'Action') + '|' + p.action; },
            name: function (p) { return p.action; },
            tier: function (p) { return p.tier; }
        },
        tier: {
            label: 'Tier level', kind: 'tier',
            id: function (p) { return 'T:' + p.tier; },
            name: function (p) { return EOCE.tier(p.tier).label; },
            tier: function (p) { return p.tier; }
        }
    },
    COLUMN_ORDER: ['system', 'role', 'service', 'action', 'tier'],
    DEFAULT_COLUMNS: ['role', 'service', 'tier'],
    NODE_CAP: 900,

    // Selectable visualizations. They all share the same filters, stats, legend,
    // deep-link focus and the contributing-actions table below the chart.
    VIEW_MODES: [
        { key: 'sankey', label: 'Sankey', hint: 'Flow of role \u2192 service \u2192 action \u2192 tier' },
        { key: 'icicle', label: 'Icicle', hint: 'Zoomable space-filling hierarchy' },
        { key: 'treemap', label: 'Treemap', hint: 'Area = number of role actions' },
        { key: 'heatmap', label: 'Heatmap', hint: 'Roles \u00d7 services, coloured by highest tier' }
    ],
    HEATMAP_CELL_CAP: 20000,

    state: null,

    // ---- Lifecycle -------------------------------------------------------
    render: function (el, params) {
        var self = this;
        if (!this.state) {
            this.state = {
                columns: this.DEFAULT_COLUMNS.slice(),
                viewMode: 'sankey',
                systems: {},
                tiers: {},
                privOnly: false,
                mismatchOnly: false,
                service: 'all',
                q: '',
                tableFilter: null,
                linkFocus: null,
                icicleFocusId: null
            };
            EOCE.rolesSystemKeys().forEach(function (k) { self.state.systems[k] = true; });
            EOCE.TIER_ORDER.forEach(function (t) { self.state.tiers[t] = true; });
        }

        var sysKeys = EOCE.rolesSystemKeys();
        var rolePaths = sysKeys.map(function (k) { return EOCE.RBAC_SYSTEMS[k].file; });
        var docsCfg = EOCE.DOCS_COMPARE.EntraID;
        return EOCE.util.loadScripts([
            'assets/vendor/d3.min.js',
            'assets/vendor/d3-sankey.min.js'
        ]).catch(function () {
            // draw() renders a useful fallback when the vendored libraries are unavailable.
        }).then(function () {
            return Promise.all([
                EOCE.data.loadAll(rolePaths),
                docsCfg ? EOCE.data.load(docsCfg.file).catch(function () { return []; }) : Promise.resolve([])
            ]);
        }).then(function (res) {
            self.paths = self.buildPaths(sysKeys, res[0], res[1]);

            el.innerHTML =
                '<div class="view">' +
                '<div class="page-head"><h1>Overview &middot; Enterprise Access Model Map</h1>' +
                '<p>Browse the EntraOps classification &mdash; <strong>role system &rarr; role &rarr; service &rarr; role action &rarr; tier level</strong> &mdash; and see which roles and role actions reach the <strong>Control Plane</strong>, and exactly which actions are responsible. ' +
                'Switch between a <strong>Sankey</strong> flow, a zoomable <strong>icicle</strong>, a <strong>treemap</strong>, or a roles &times; services <strong>heatmap</strong>. ' +
                'Filter by system, service, privileged roles, or use the mismatch filter to focus on role actions that differ between the live definition and the Microsoft Learn reference.</p></div>' +
                '<div id="tmToolbar"></div>' +
                '<div id="tmLegend" class="tm-legend"></div>' +
                '<div id="tmStats" class="tm-stats"></div>' +
                '<div class="tm-diagram-wrap"><div id="tmEmpty" class="tm-empty" style="display:none;"></div><svg id="tmSankey"></svg></div>' +
                '<div class="tm-contrib">' +
                '<div class="tm-contrib-head"><div class="section-title" style="margin:0;">Contributing role actions</div>' +
                '<span id="tmFocusTag" class="chip" style="display:none;"></span>' +
                '<button id="tmClearFocus" class="btn small" type="button" style="display:none;">Clear selection</button>' +
                '<span class="toolbar-meta" id="tmContribCount"></span></div>' +
                '<p class="muted" style="margin:2px 0 10px;font-size:12px;">Click any node in the diagram to focus this list on the role actions flowing through it &mdash; this is the "why" behind a tier classification.</p>' +
                '<div class="table-wrap"><table class="grid-table" id="tmContribTable"></table></div></div>' +
                '</div>';

            self.tooltip = document.getElementById('tmTooltip');
            if (!self.tooltip) {
                self.tooltip = document.createElement('div');
                self.tooltip.id = 'tmTooltip';
                self.tooltip.className = 'tm-tooltip';
                self.tooltip.style.display = 'none';
                document.body.appendChild(self.tooltip);
                // The tooltip is appended to <body>, so it outlives this view - hide it
                // on any navigation so it can't linger over another view.
                window.addEventListener('hashchange', function () { self.tooltip.style.display = 'none'; });
            }
            self.tooltip.style.display = 'none';

            // Deep-link focus: #overview/role/<sys>/<roleId> or #overview/action/<sys>/<action>/<actionType>
            self.pendingFocus = null;
            // Re-rendering without focus params ends a previous deep-link focus, so
            // restore the systems selection scopeToFocus narrowed (see scopeToFocus).
            if (self.state.linkFocus && self._preFocusSystems) {
                self.state.systems = self._preFocusSystems;
                self._preFocusSystems = null;
            }
            self.state.linkFocus = null;
            if (params && params[0]) {
                var kind = params[0];
                if (kind === 'role' && params[1] && params[2]) {
                    self.scopeToFocus(params[1], { type: 'role', sys: params[1], key: params[2] });
                    self.pendingFocus = { column: 'role', id: 'R:' + params[1] + '|' + params[2] };
                } else if (kind === 'action' && params[1] && params[2]) {
                    // 'Action' and 'DataAction' are both valid deep-link action types
                    // (actions.js sends 'Action' for ordinary actions).
                    var actionType = params[3] === 'DataAction' ? 'DataAction' : 'Action';
                    self.scopeToFocus(params[1], { type: 'action', sys: params[1], key: params[2], actionType: actionType });
                    if (self.state.columns.indexOf('action') === -1) self.state.columns.push('action');
                    self.pendingFocus = { column: 'action', id: 'A:' + params[1] + '|' + actionType + '|' + params[2] };
                }
            }

            self.renderToolbar();
            self.renderLegend();
            self.draw();
        });
    },

    // Narrow the view to a single deep-linked role/action so the Sankey stays
    // readable (and never trips the node cap). Keeps every tier visible and
    // includes Microsoft Learn-only roles so the focused entity always appears.
    scopeToFocus: function (sys, focus) {
        var s = this.state;
        // Remember the systems selection so ending the focus (clear button or a
        // re-render without focus params) can restore it instead of leaving the
        // view narrowed to a single system. Only the first scoping in a focus
        // session records it - consecutive deep links keep the true pre-focus state.
        if (!this._preFocusSystems) {
            var saved = {};
            Object.keys(s.systems).forEach(function (k) { saved[k] = s.systems[k]; });
            this._preFocusSystems = saved;
        }
        EOCE.rolesSystemKeys().forEach(function (k) { s.systems[k] = (k === sys); });
        EOCE.TIER_ORDER.forEach(function (t) { s.tiers[t] = true; });
        s.privOnly = false;
        s.mismatchOnly = false;
        s.service = 'all';
        s.q = '';
        s.tableFilter = null;
        s.linkFocus = focus;
    },

    clearLinkFocus: function () {
        var s = this.state;
        s.linkFocus = null;
        if (this._preFocusSystems) {
            s.systems = this._preFocusSystems;
            this._preFocusSystems = null;
        } else {
            EOCE.rolesSystemKeys().forEach(function (k) { s.systems[k] = true; });
        }
        this.renderToolbar();
        this.draw();
    },

    // ---- Data ------------------------------------------------------------
    buildPaths: function (sysKeys, roleSets, docsArray) {
        // Prefer the pre-built dataset embedded by Update-EntraOpsClassificationExplorerData.
        if (window.EOCE_TIER_MAP && Array.isArray(window.EOCE_TIER_MAP.paths) && window.EOCE_TIER_MAP.paths.length) {
            return window.EOCE_TIER_MAP.paths;
        }

        // Build per-role MS Learn action maps (EntraID only) for two-way mismatch detection:
        //   graphOnlyDiff=true  → action is in the live Graph definition but absent from MS Learn
        //   docsOnly=true       → action (or entire role) exists only in MS Learn, not in Graph
        var docsActionsByRole = {}; // { roleId: { lowerAction: true } }
        var docsRoles = {};         // { roleId: role }
        if (docsArray && docsArray.length) {
            docsArray.forEach(function (role) {
                if (!role.RoleId) return;
                var acts = {};
                EOCE.rolePerms(role).forEach(function (p) {
                    if (p.AuthorizedResourceAction) acts[String(p.AuthorizedResourceAction).toLowerCase()] = true;
                });
                docsActionsByRole[role.RoleId] = acts;
                docsRoles[role.RoleId] = role;
            });
        }

        var paths = [];
        var graphActionsByRole = {}; // { roleId: { lowerAction: true } } for EntraID

        // Pass 1: Graph definition paths, flagging Graph-only actions (graphOnlyDiff).
        sysKeys.forEach(function (k, i) {
            (roleSets[i] || []).forEach(function (role) {
                var roleClass = (role.Classification && role.Classification.EAMTierLevelName) || 'Unclassified';
                if (!EOCE.TIERS[roleClass]) roleClass = 'Unclassified';
                var mismatchSet = null; // actions in Graph that are absent from MS Learn
                if (k === 'EntraID' && role.RoleId) {
                    var graphActs = {};
                    EOCE.rolePerms(role).forEach(function (p) {
                        if (p.AuthorizedResourceAction) graphActs[String(p.AuthorizedResourceAction).toLowerCase()] = true;
                    });
                    graphActionsByRole[role.RoleId] = graphActs;
                    var docsActs = docsActionsByRole[role.RoleId]; // undefined = role not in MS Learn
                    if (docsActs !== undefined) {
                        mismatchSet = {};
                        Object.keys(graphActs).forEach(function (la) { if (!docsActs[la]) mismatchSet[la] = true; });
                    }
                }
                EOCE.rolePerms(role).forEach(function (p) {
                    var la = String(p.AuthorizedResourceAction || '').toLowerCase();
                    paths.push({
                        sys: k,
                        roleId: role.RoleId,
                        role: role.RoleName,
                        priv: role.isPrivileged === true,
                        roleClass: roleClass,
                        cats: role.Categories || '',
                        service: p.Category || '(uncategorized)',
                        action: p.AuthorizedResourceAction,
                        tier: EOCE.TIERS[p.EAMTierLevelName] ? p.EAMTierLevelName : 'Unclassified',
                        docsOnly: false,
                        graphOnlyDiff: !!(mismatchSet && mismatchSet[la])
                    });
                });
            });
        });

        // Pass 2: MS Learn-only paths.
        //   - Role absent from Graph entirely: add all its actions (docsOnly=true).
        //   - Role in both sources: add only actions that are absent from the Graph definition.
        Object.keys(docsRoles).forEach(function (roleId) {
            var role = docsRoles[roleId];
            var roleClass = (role.Classification && role.Classification.EAMTierLevelName) || 'Unclassified';
            if (!EOCE.TIERS[roleClass]) roleClass = 'Unclassified';
            var graphActs = graphActionsByRole[roleId] || null; // null = role not in Graph
            EOCE.rolePerms(role).forEach(function (p) {
                var la = String(p.AuthorizedResourceAction || '').toLowerCase();
                if (graphActs !== null && graphActs[la]) return; // already covered by a Graph path
                paths.push({
                    sys: 'EntraID',
                    roleId: role.RoleId,
                    role: role.RoleName,
                    priv: role.isPrivileged === true,
                    roleClass: roleClass,
                    cats: role.Categories || '',
                    service: p.Category || '(uncategorized)',
                    action: p.AuthorizedResourceAction,
                    actionType: p.ActionType === 'DataAction' ? 'DataAction' : 'Action',
                    tier: EOCE.TIERS[p.EAMTierLevelName] ? p.EAMTierLevelName : 'Unclassified',
                    docsOnly: true,
                    graphOnlyDiff: false
                });
            });
        });

        return paths;
    },

    servicesFor: function () {
        var s = this.state, set = {};
        (this.paths || []).forEach(function (p) {
            if (!s.systems[p.sys]) return;
            if (!s.mismatchOnly && p.docsOnly) return;
            if (s.mismatchOnly && !p.docsOnly && !p.graphOnlyDiff) return;
            set[p.service] = true;
        });
        return Object.keys(set).sort(function (a, b) { return a.toLowerCase() < b.toLowerCase() ? -1 : 1; });
    },

    filteredPaths: function () {
        var s = this.state, q = (s.q || '').toLowerCase();
        var lf = s.linkFocus;
        return (this.paths || []).filter(function (p) {
            if (lf) {
                if (p.sys !== lf.sys) return false;
                if (lf.type === 'role' && p.roleId !== lf.key) return false;
                if (lf.type === 'action' && (p.action !== lf.key || (lf.actionType && (p.actionType === 'DataAction' ? 'DataAction' : 'Action') !== lf.actionType))) return false;
            }
            if (!s.systems[p.sys]) return false;
            if (!s.mismatchOnly && p.docsOnly) return false;
            if (s.mismatchOnly && !p.docsOnly && !p.graphOnlyDiff) return false;
            if (s.privOnly && !p.priv) return false;
            if (s.service !== 'all' && p.service !== s.service) return false;
            if (!s.tiers[p.tier]) return false;
            if (q) {
                var hay = (p.role + ' ' + p.service + ' ' + p.action + ' ' + p.cats).toLowerCase();
                if (hay.indexOf(q) === -1) return false;
            }
            return true;
        });
    },

    // ---- Toolbar ---------------------------------------------------------
    renderToolbar: function () {
        var self = this, s = this.state;
        var esc = EOCE.util.escapeHtml;
        var html = '<div class="toolbar tm-toolbar">';

        // Deep-link focus banner
        if (s.linkFocus) {
            var lf = s.linkFocus, lfLabel = lf.key;
            if (lf.type === 'role') {
                var match = (this.paths || []).find(function (p) { return p.sys === lf.sys && p.roleId === lf.key; });
                if (match) lfLabel = match.role;
            }
            var sysShort = (EOCE.RBAC_SYSTEMS[lf.sys] && EOCE.RBAC_SYSTEMS[lf.sys].short) || lf.sys;
            html += '<div class="tm-focus-banner" style="flex-basis:100%;">' +
                '<span class="chip brand">Focused on ' + esc(lf.type) + ': ' + esc(sysShort) + ' &middot; ' + esc(lfLabel) + '</span>' +
                '<button id="tmClearLinkFocus" class="btn small">Clear focus &times;</button></div>';
        }

        // Visualization mode switch
        html += '<div class="tm-modes" id="tmModes" role="tablist">';
        this.VIEW_MODES.forEach(function (m) {
            html += '<button type="button" class="tm-mode' + (s.viewMode === m.key ? ' on' : '') + '" data-mode="' + m.key + '" title="' + esc(m.hint) + '">' + esc(m.label) + '</button>';
        });
        html += '</div>';

        html += '<div class="search"><span class="search-ico">&#128269;</span>' +
            '<input id="tmSearch" type="text" placeholder="Filter by role, service or action&hellip;" value="' + esc(s.q) + '"></div>';

        // Column (flow) toggles - apply to the hierarchy charts, not the fixed heatmap
        if (s.viewMode !== 'heatmap') {
            html += '<div class="tm-group"><span class="tm-group-label">Columns</span><div class="tm-checks" id="tmCols">';
            this.COLUMN_ORDER.forEach(function (k) {
                html += '<label class="tm-check"><input type="checkbox" data-col="' + k + '"' +
                    (s.columns.indexOf(k) !== -1 ? ' checked' : '') + '>' + esc(self.COLUMNS[k].label) + '</label>';
            });
            html += '</div></div>';
        }

        // System toggles
        html += '<div class="tm-group"><span class="tm-group-label">Systems</span><div class="tm-checks" id="tmSystems">';
        EOCE.rolesSystemKeys().forEach(function (k) {
            html += '<label class="tm-check"><input type="checkbox" data-sys="' + k + '"' +
                (s.systems[k] ? ' checked' : '') + '>' + esc(EOCE.RBAC_SYSTEMS[k].short) + '</label>';
        });
        html += '</div></div>';

        // Service / category select
        var services = this.servicesFor();
        if (s.service !== 'all' && services.indexOf(s.service) === -1) s.service = 'all';
        html += '<select class="filter" id="tmService" title="Filter by service / classification category">' +
            '<option value="all">All services (' + services.length + ')</option>';
        services.forEach(function (c) {
            html += '<option value="' + esc(c) + '"' + (s.service === c ? ' selected' : '') + '>' + esc(c) + '</option>';
        });
        html += '</select>';

        // Tier toggles
        html += '<div class="tier-toggles" id="tmTiers">';
        EOCE.TIER_ORDER.forEach(function (t) {
            html += '<span class="tier-toggle tier-' + t.toLowerCase() + (s.tiers[t] ? ' on' : '') + '" data-tier="' + t + '">' +
                '<span class="tier-dot"></span>' + EOCE.tier(t).short + '</span>';
        });
        html += '</div>';

        html += '<label class="chip" style="cursor:pointer;gap:6px;"><input type="checkbox" id="tmPriv"' + (s.privOnly ? ' checked' : '') + '> Privileged only</label>';
        html += '<label class="chip" style="cursor:pointer;gap:6px;" title="Show only role actions where the live Microsoft Graph definition and the Microsoft Learn permissions reference disagree \u2014 includes actions only in the Graph definition (not documented) and actions only in Microsoft Learn (not in the live definition)">' +
            '<input type="checkbox" id="tmDocs"' + (s.mismatchOnly ? ' checked' : '') + '> Docs/Role Definition Mismatch only</label>';

        html += '</div>';
        document.getElementById('tmToolbar').innerHTML = html;

        var clearFocusBtn = document.getElementById('tmClearLinkFocus');
        if (clearFocusBtn) clearFocusBtn.addEventListener('click', function () { self.clearLinkFocus(); });

        document.getElementById('tmModes').addEventListener('click', function (e) {
            var b = e.target.closest('[data-mode]'); if (!b) return;
            var m = b.getAttribute('data-mode');
            if (m === s.viewMode) return;
            s.viewMode = m;
            s.tableFilter = null;
            s.icicleFocusId = null;
            self.renderToolbar();
            self.renderLegend();
            self.draw();
        });

        document.getElementById('tmSearch').addEventListener('input', EOCE.util.debounce(function (e) {
            s.q = e.target.value.trim(); self.draw();
        }, 180));
        var colsEl = document.getElementById('tmCols');
        if (colsEl) colsEl.addEventListener('change', function (e) {
            var k = e.target.getAttribute('data-col'); if (!k) return;
            if (e.target.checked) { if (s.columns.indexOf(k) === -1) s.columns.push(k); }
            else { s.columns = s.columns.filter(function (c) { return c !== k; }); }
            s.icicleFocusId = null;
            self.draw();
        });
        document.getElementById('tmSystems').addEventListener('change', function (e) {
            var k = e.target.getAttribute('data-sys'); if (!k) return;
            s.systems[k] = e.target.checked;
            self.renderToolbar(); self.draw();
        });
        document.getElementById('tmService').addEventListener('change', function (e) {
            s.service = e.target.value; self.draw();
        });
        document.getElementById('tmTiers').addEventListener('click', function (e) {
            var b = e.target.closest('[data-tier]'); if (!b) return;
            var t = b.getAttribute('data-tier');
            s.tiers[t] = !s.tiers[t];
            b.classList.toggle('on', s.tiers[t]);
            self.draw();
        });
        document.getElementById('tmPriv').addEventListener('change', function (e) {
            s.privOnly = e.target.checked; self.draw();
        });
        document.getElementById('tmDocs').addEventListener('change', function (e) {
            s.mismatchOnly = e.target.checked; self.renderToolbar(); self.draw();
        });
    },

    renderLegend: function () {
        var html = '';
        EOCE.TIER_ORDER.forEach(function (t) {
            var tier = EOCE.tier(t);
            html += '<span class="tm-leg-item"><span class="tm-sw" style="background:' + tier.color + '"></span>' +
                EOCE.util.escapeHtml(tier.label) + '</span>';
        });
        var caps = {
            sankey: 'Stream colour = highest-privilege tier reached along the flow',
            icicle: 'Block colour = highest-privilege tier reached &middot; click to zoom in, click again to zoom out',
            treemap: 'Tile area = number of role actions &middot; colour = highest-privilege tier',
            heatmap: 'Cell colour = highest-privilege tier a role reaches in that service'
        };
        var cap = caps[this.state.viewMode] || caps.sankey;
        html += '<span class="tm-leg-item muted" style="margin-left:auto;">' + cap + '</span>';
        document.getElementById('tmLegend').innerHTML = html;
    },

    // ---- Graph build -----------------------------------------------------
    tierRank: function (name) {
        var i = EOCE.TIER_ORDER.indexOf(name);
        return i < 0 ? 99 : i;
    },

    buildGraph: function (paths, activeCols) {
        var self = this;
        var nodeMap = {};
        var linkMap = {};

        function ensureNode(colKey, p) {
            var col = self.COLUMNS[colKey];
            var id = col.id(p);
            if (!nodeMap[id]) {
                nodeMap[id] = {
                    id: id,
                    name: col.name(p),
                    tier: col.tier(p),
                    kind: col.kind,
                    meta: col.meta ? col.meta(p) : null,
                    column: colKey,
                    _rank: undefined
                };
            }
            return id;
        }

        paths.forEach(function (p) {
            var ids = activeCols.map(function (c) { return ensureNode(c, p); });
            // Aggregate the highest-privilege tier flowing through service/system nodes.
            activeCols.forEach(function (c, idx) {
                var n = nodeMap[ids[idx]];
                if (n.kind === 'service' || n.kind === 'system') {
                    var r = self.tierRank(p.tier);
                    if (n._rank === undefined || r < n._rank) { n._rank = r; n.tier = EOCE.TIER_ORDER[r]; }
                }
            });
            for (var i = 0; i < ids.length - 1; i++) {
                var key = ids[i] + '\u2192' + ids[i + 1];
                var link = linkMap[key];
                if (!link) {
                    link = { source: ids[i], target: ids[i + 1], value: 0, rank: 99 };
                    linkMap[key] = link;
                }
                link.value += 1;
                var lr = self.tierRank(p.tier);
                if (lr < link.rank) link.rank = lr;
            }
        });

        var nodes = Object.keys(nodeMap).map(function (k) { return nodeMap[k]; });
        var index = {};
        nodes.forEach(function (n, i) { index[n.id] = i; });
        var links = Object.keys(linkMap).map(function (k) {
            var l = linkMap[k];
            return { source: index[l.source], target: index[l.target], value: l.value, rank: l.rank };
        });
        return { nodes: nodes, links: links };
    },

    nodeColor: function (n) {
        if (n.tier && EOCE.TIERS[n.tier]) return EOCE.tier(n.tier).color;
        return '#8b949e';
    },

    // ---- Draw ------------------------------------------------------------
    draw: function () {
        var self = this;
        var empty = document.getElementById('tmEmpty');
        var svg = document.getElementById('tmSankey');
        var mode = this.state.viewMode || 'sankey';

        var d3Ready = typeof d3 !== 'undefined';
        var sankeyReady = d3Ready && typeof d3.sankey !== 'undefined';
        if (!d3Ready || (mode === 'sankey' && !sankeyReady)) {
            svg.innerHTML = '';
            empty.style.display = '';
            empty.innerHTML = 'The visualization library could not be loaded. The EAM Map needs the d3 / d3-sankey scripts ' +
                'in <code>assets/vendor/</code> (referenced from index.html). Make sure those files are present, or browse the data via the ' +
                '<a href="#roles">Roles</a> and <a href="#actions">Role Actions</a> views.';
            this.renderStats([]);
            this.renderContrib();
            return;
        }

        this._clearHighlight = null;
        this._focusMark = null;
        var paths = this.filteredPaths();
        this.renderStats(paths);
        d3.select(svg).selectAll('*').remove();
        svg.innerHTML = '';
        svg.removeAttribute('viewBox');
        svg.removeAttribute('style');

        if (!paths.length) {
            empty.style.display = '';
            empty.textContent = 'No classification data matches the current filters.';
            this.renderContrib();
            return;
        }

        var drew;
        if (mode === 'icicle') drew = this.drawIcicle(paths);
        else if (mode === 'treemap') drew = this.drawTreemap(paths);
        else if (mode === 'heatmap') drew = this.drawHeatmap(paths);
        else drew = this.drawSankeyMode(paths);

        this.renderContrib();

        if (drew !== false && this.pendingFocus) {
            var pf = this.pendingFocus; this.pendingFocus = null;
            this.applyPendingFocus(pf, mode);
        }
    },

    applyPendingFocus: function (pf, mode) {
        if (mode === 'sankey') { this.focusNode(pf.id); return; }
        // For hierarchy/heatmap modes, focus the contributing-actions table and
        // visually emphasise the matching marks.
        var label = pf.id;
        // Derive candidate ids via COLUMNS so the lookup matches the real node id
        // shape (action ids include the action type segment).
        var col = this.COLUMNS[pf.column];
        var match = (this.paths || []).find(function (p) {
            return col.id(p) === pf.id;
        });
        if (match) label = pf.column === 'role' ? match.role : match.action;
        this.state.tableFilter = { column: pf.column, id: pf.id, label: label };
        this.renderContrib();
        if (this._focusMark) this._focusMark(pf.id);
        var wrap = document.querySelector('.tm-diagram-wrap');
        if (wrap && wrap.scrollIntoView) wrap.scrollIntoView({ behavior: 'smooth', block: 'start' });
    },

    drawSankeyMode: function (paths) {
        var self = this;
        var empty = document.getElementById('tmEmpty');
        var svg = document.getElementById('tmSankey');
        var activeCols = this.COLUMN_ORDER.filter(function (k) { return self.state.columns.indexOf(k) !== -1; });

        if (activeCols.length < 2) {
            empty.style.display = '';
            empty.textContent = 'Select at least two columns to draw a flow.';
            return false;
        }
        var graph = this.buildGraph(paths, activeCols);
        if (graph.nodes.length > this.NODE_CAP) {
            empty.style.display = '';
            empty.innerHTML = 'This view would draw <strong>' + EOCE.util.formatNumber(graph.nodes.length) + '</strong> nodes, which is too dense to be useful. ' +
                'Narrow the result first &mdash; pick a single system, a service, enable <em>Privileged only</em>, or drop the <em>Role action</em> column.';
            return false;
        }
        empty.style.display = 'none';
        this.drawSankey(graph);
        this._clearHighlight = function () {
            if (self._nodeSel) self._nodeSel.classed('dim', false);
            if (self._linkSel) self._linkSel.classed('dim', false);
        };
        return true;
    },

    drawSankey: function (graph) {
        var self = this;
        var d3svg = d3.select('#tmSankey');
        var wrap = document.querySelector('.tm-diagram-wrap');
        var width = Math.max(820, (wrap ? wrap.clientWidth : 960) - 8);
        var rowH = 20;
        var height = Math.max(420, graph.nodes.length * rowH);

        d3svg.attr('width', width).attr('height', height);
        d3svg.selectAll('*').remove();

        var sankey = d3.sankey()
            .nodeWidth(15)
            .nodePadding(9)
            .extent([[8, 8], [width - 8, height - 8]]);

        var layout;
        try {
            layout = sankey({
                nodes: graph.nodes.map(function (d) { return Object.assign({}, d); }),
                links: graph.links.map(function (d) { return Object.assign({}, d); })
            });
        } catch (e) {
            d3svg.selectAll('*').remove();
            var empty = document.getElementById('tmEmpty');
            empty.style.display = '';
            empty.textContent = 'Unable to lay out the flow (a cycle was detected). Try different columns.';
            return;
        }

        var nodes = layout.nodes, links = layout.links;

        function linkColor(d) { return EOCE.tier(EOCE.TIER_ORDER[d.rank] || 'Unclassified').color; }
        function linkOpacity(d) { return d.rank === 0 ? 0.55 : d.rank === 1 ? 0.42 : d.rank === 2 ? 0.3 : 0.2; }

        var linkSel = d3svg.append('g').attr('class', 'tm-links').selectAll('path')
            .data(links).join('path')
            .attr('class', 'tm-link')
            .attr('d', d3.sankeyLinkHorizontal())
            .attr('stroke', linkColor)
            .attr('stroke-opacity', linkOpacity)
            .attr('stroke-width', function (d) { return Math.max(1, d.width); })
            .on('mousemove', function (ev, d) {
                self.showTip(ev, '<b>' + EOCE.util.escapeHtml(d.source.name) + '</b> &rarr; <b>' + EOCE.util.escapeHtml(d.target.name) + '</b><br>' +
                    d.value + ' role-action path(s)<br>' + EOCE.util.escapeHtml(EOCE.tier(EOCE.TIER_ORDER[d.rank] || 'Unclassified').label));
            })
            .on('mouseleave', function () { self.hideTip(); });

        var nodeSel = d3svg.append('g').attr('class', 'tm-nodes').selectAll('g')
            .data(nodes).join('g').attr('class', 'tm-node');

        nodeSel.append('rect')
            .attr('x', function (d) { return d.x0; })
            .attr('y', function (d) { return d.y0; })
            .attr('width', function (d) { return d.x1 - d.x0; })
            .attr('height', function (d) { return Math.max(2, d.y1 - d.y0); })
            .attr('rx', 2)
            .attr('fill', function (d) { return self.nodeColor(d); })
            .style('cursor', 'pointer')
            .on('mousemove', function (ev, d) {
                self.showTip(ev, '<b>' + EOCE.util.escapeHtml(d.name) + '</b>' + (d.meta ? ' &middot; ' + EOCE.util.escapeHtml(d.meta) : '') +
                    '<br>' + EOCE.util.escapeHtml(self.COLUMNS[d.column].label) +
                    (d.tier ? '<br>' + EOCE.util.escapeHtml(EOCE.tier(d.tier).label) : '') +
                    '<br>' + d.value.toFixed(0) + ' role-action path(s)');
            })
            .on('mouseleave', function () { self.hideTip(); })
            .on('click', function (ev, d) {
                ev.stopPropagation();
                self.highlight(d, nodeSel, linkSel);
                self.setFocusFromNode(d);
            });

        nodeSel.append('text')
            .attr('x', function (d) { return d.x0 < width / 2 ? d.x1 + 6 : d.x0 - 6; })
            .attr('y', function (d) { return (d.y0 + d.y1) / 2; })
            .attr('dy', '0.35em')
            .attr('text-anchor', function (d) { return d.x0 < width / 2 ? 'start' : 'end'; })
            .attr('class', 'tm-node-label')
            .text(function (d) { return self.truncate(d.name, 40); })
            .filter(function (d) { return d.y1 - d.y0 < 9; })
            .remove();

        d3svg.on('click', function (ev) {
            if (ev.target.tagName === 'svg') {
                nodeSel.classed('dim', false);
                linkSel.classed('dim', false);
            }
        });

        this._nodeSel = nodeSel;
        this._linkSel = linkSel;
        this._layoutNodes = nodes;
    },

    // ---- Hierarchy (icicle / treemap) ------------------------------------
    // Nest the filtered paths by the active columns. Every node tracks the count
    // of role-action paths beneath it and the highest-privilege tier rank reached,
    // so blocks/tiles can be coloured the same way as the Sankey.
    buildHierarchy: function (paths, activeCols) {
        var self = this;
        var root = { name: 'All systems', id: '__root', column: null, kind: 'root', children: [], _map: {}, rank: 99, count: 0 };
        paths.forEach(function (p) {
            var node = root, r = self.tierRank(p.tier);
            node.count++; if (r < node.rank) node.rank = r;
            activeCols.forEach(function (c) {
                var col = self.COLUMNS[c], id = col.id(p);
                var child = node._map[id];
                if (!child) {
                    child = { name: col.name(p), id: id, column: c, kind: col.kind, children: [], _map: {}, rank: 99, count: 0, meta: col.meta ? col.meta(p) : null };
                    node._map[id] = child; node.children.push(child);
                }
                child.count++; if (r < child.rank) child.rank = r;
                node = child;
            });
        });
        return root;
    },

    rankColor: function (rank) {
        var t = EOCE.TIER_ORDER[rank];
        return t ? EOCE.tier(t).color : '#8b949e';
    },

    setFocusFromHierNode: function (d) {
        if (!d || d.data.column == null) { this.clearFocus(); return; }
        this.setFocusFromNode({ column: d.data.column, id: d.data.id, name: d.data.name });
    },

    // ---- Icicle (zoomable partition) -------------------------------------
    drawIcicle: function (paths) {
        var self = this, s = this.state;
        var empty = document.getElementById('tmEmpty');
        var activeCols = this.COLUMN_ORDER.filter(function (k) { return s.columns.indexOf(k) !== -1; });
        if (!activeCols.length) {
            empty.style.display = ''; empty.textContent = 'Select at least one column to build the icicle.';
            return false;
        }
        empty.style.display = 'none';

        var rootData = this.buildHierarchy(paths, activeCols);
        var root = d3.hierarchy(rootData, function (d) { return d.children; })
            .sum(function (d) { return (d.children && d.children.length) ? 0 : d.count; })
            .sort(function (a, b) { return (a.data.rank - b.data.rank) || (b.value - a.value); });

        var wrap = document.querySelector('.tm-diagram-wrap');
        var width = Math.max(820, (wrap ? wrap.clientWidth : 960) - 8);
        var leaves = root.leaves().length;
        var height = Math.max(420, Math.min(leaves * 13, 18000));

        d3.partition().size([height, width]).padding(0)(root);

        var focus = root;
        if (s.icicleFocusId) {
            root.each(function (d) { if (d.data.id === s.icicleFocusId) focus = d; });
        }

        var svg = d3.select('#tmSankey').attr('width', width).attr('height', height);
        var fy0 = focus.x0, fy1 = focus.x1;
        function ry0(d) { return (d.x0 - fy0) / (fy1 - fy0) * height; }
        function ry1(d) { return (d.x1 - fy0) / (fy1 - fy0) * height; }

        var visible = focus.descendants();
        var cell = svg.append('g').selectAll('g').data(visible).join('g')
            .attr('class', 'tm-ice-cell')
            .attr('transform', function (d) { return 'translate(' + (d.y0 - focus.y0) + ',' + ry0(d) + ')'; });

        cell.append('rect')
            .attr('width', function (d) { return Math.max(0, d.y1 - d.y0 - 1); })
            .attr('height', function (d) { return Math.max(0, ry1(d) - ry0(d) - 1); })
            .attr('rx', 2)
            .attr('fill', function (d) { return self.rankColor(d.data.rank); })
            .attr('class', function (d) { return s.tableFilter && s.tableFilter.id === d.data.id ? 'tm-ice-rect sel' : 'tm-ice-rect'; })
            .style('cursor', 'pointer')
            .on('mousemove', function (ev, d) {
                self.showTip(ev, '<b>' + EOCE.util.escapeHtml(d.data.name) + '</b>' + (d.data.meta ? ' &middot; ' + EOCE.util.escapeHtml(d.data.meta) : '') +
                    '<br>' + EOCE.util.escapeHtml(self.COLUMNS[d.data.column] ? self.COLUMNS[d.data.column].label : 'All') +
                    '<br>' + EOCE.util.escapeHtml(EOCE.tier(EOCE.TIER_ORDER[d.data.rank] || 'Unclassified').label) +
                    '<br>' + EOCE.util.formatNumber(d.data.count) + ' role-action path(s)' +
                    (d.children ? '<br><span class="muted">click to zoom</span>' : ''));
            })
            .on('mouseleave', function () { self.hideTip(); })
            .on('click', function (ev, d) {
                ev.stopPropagation();
                if (d.data.column == null) return;
                if (d.children && d.children.length) {
                    s.icicleFocusId = (d === focus)
                        ? (focus.parent && focus.parent.data.id !== '__root' ? focus.parent.data.id : null)
                        : d.data.id;
                    s.tableFilter = { column: d.data.column, id: d.data.id, label: d.data.name };
                    self.draw();
                } else {
                    self.setFocusFromHierNode(d);
                    svg.selectAll('rect.tm-ice-rect').classed('sel', function (n) { return n.data.id === d.data.id; });
                }
            });

        cell.append('text')
            .attr('class', 'tm-node-label')
            .attr('x', 5)
            .attr('y', function (d) { return (ry1(d) - ry0(d)) / 2; })
            .attr('dy', '0.35em')
            .text(function (d) {
                var w = d.y1 - d.y0, h = ry1(d) - ry0(d);
                if (h < 11 || w < 34) return '';
                return self.truncate(d.data.name, Math.max(3, Math.floor(w / 7)));
            });

        svg.on('click', function (ev) {
            if (ev.target.tagName === 'svg') {
                if (s.icicleFocusId) { s.icicleFocusId = null; self.draw(); }
                else self.clearFocus();
            }
        });

        this._clearHighlight = function () {
            svg.selectAll('rect.tm-ice-rect').classed('sel', false);
        };
        this._focusMark = function (id) {
            svg.selectAll('rect.tm-ice-rect').classed('sel', function (n) { return n.data.id === id; });
        };
        return true;
    },

    // ---- Treemap ---------------------------------------------------------
    drawTreemap: function (paths) {
        var self = this, s = this.state;
        var empty = document.getElementById('tmEmpty');
        var activeCols = this.COLUMN_ORDER.filter(function (k) { return s.columns.indexOf(k) !== -1; });
        if (!activeCols.length) {
            empty.style.display = ''; empty.textContent = 'Select at least one column to build the treemap.';
            return false;
        }
        empty.style.display = 'none';

        var rootData = this.buildHierarchy(paths, activeCols);
        var root = d3.hierarchy(rootData, function (d) { return d.children; })
            .sum(function (d) { return (d.children && d.children.length) ? 0 : d.count; })
            .sort(function (a, b) { return (a.data.rank - b.data.rank) || (b.value - a.value); });

        var wrap = document.querySelector('.tm-diagram-wrap');
        var width = Math.max(820, (wrap ? wrap.clientWidth : 960) - 8);
        var height = Math.max(480, Math.round(width * 0.6));

        d3.treemap().size([width, height]).paddingInner(1).paddingOuter(1).round(true)(root);

        var svg = d3.select('#tmSankey').attr('width', width).attr('height', height);
        var leaves = root.leaves();
        var cell = svg.append('g').selectAll('g').data(leaves).join('g')
            .attr('transform', function (d) { return 'translate(' + d.x0 + ',' + d.y0 + ')'; });

        cell.append('rect')
            .attr('width', function (d) { return Math.max(0, d.x1 - d.x0); })
            .attr('height', function (d) { return Math.max(0, d.y1 - d.y0); })
            .attr('rx', 1)
            .attr('fill', function (d) { return self.rankColor(d.data.rank); })
            .attr('class', function (d) { return s.tableFilter && s.tableFilter.id === d.data.id ? 'tm-tile sel' : 'tm-tile'; })
            .style('cursor', 'pointer')
            .on('mousemove', function (ev, d) {
                var anc = d.ancestors().reverse().slice(1).map(function (a) { return EOCE.util.escapeHtml(a.data.name); }).join(' &rsaquo; ');
                self.showTip(ev, '<b>' + EOCE.util.escapeHtml(d.data.name) + '</b><br>' + anc +
                    '<br>' + EOCE.util.escapeHtml(EOCE.tier(EOCE.TIER_ORDER[d.data.rank] || 'Unclassified').label) +
                    '<br>' + EOCE.util.formatNumber(d.data.count) + ' role-action path(s)');
            })
            .on('mouseleave', function () { self.hideTip(); })
            .on('click', function (ev, d) {
                ev.stopPropagation();
                self.setFocusFromHierNode(d);
                svg.selectAll('rect.tm-tile').classed('sel', function (n) { return n.data.id === d.data.id; });
            });

        cell.append('text')
            .attr('class', 'tm-node-label')
            .attr('x', 4).attr('y', 13)
            .text(function (d) {
                var w = d.x1 - d.x0, h = d.y1 - d.y0;
                if (w < 46 || h < 18) return '';
                return self.truncate(d.data.name, Math.max(3, Math.floor(w / 7)));
            });

        svg.on('click', function (ev) { if (ev.target.tagName === 'svg') self.clearFocus(); });

        this._clearHighlight = function () { svg.selectAll('rect.tm-tile').classed('sel', false); };
        this._focusMark = function (id) { svg.selectAll('rect.tm-tile').classed('sel', function (n) { return n.data.id === id; }); };
        return true;
    },

    // ---- Heatmap (roles x services) --------------------------------------
    drawHeatmap: function (paths) {
        var self = this, s = this.state;
        var empty = document.getElementById('tmEmpty');

        // Aggregate the highest-privilege tier (and action count) per role x service.
        var roleMap = {}, svcMap = {}, cells = {};
        paths.forEach(function (p) {
            var rk = p.sys + '|' + p.roleId;
            if (!roleMap[rk]) roleMap[rk] = { key: rk, sys: p.sys, roleId: p.roleId, name: p.role, priv: p.priv, docsOnly: p.docsOnly, rank: 99 };
            var r = self.tierRank(p.tier);
            if (r < roleMap[rk].rank) roleMap[rk].rank = r;
            svcMap[p.service] = (svcMap[p.service] || 0) + 1;
            var ck = rk + '||' + p.service;
            if (!cells[ck]) cells[ck] = { rank: 99, count: 0 };
            if (r < cells[ck].rank) cells[ck].rank = r;
            cells[ck].count++;
        });

        var roles = Object.keys(roleMap).map(function (k) { return roleMap[k]; })
            .sort(function (a, b) { return (a.rank - b.rank) || (a.name.toLowerCase() < b.name.toLowerCase() ? -1 : 1); });
        var services = Object.keys(svcMap)
            .sort(function (a, b) { return a.toLowerCase() < b.toLowerCase() ? -1 : 1; });

        if (roles.length * services.length > this.HEATMAP_CELL_CAP) {
            empty.style.display = '';
            empty.innerHTML = 'The heatmap would draw <strong>' + EOCE.util.formatNumber(roles.length * services.length) + '</strong> cells (' +
                EOCE.util.formatNumber(roles.length) + ' roles &times; ' + EOCE.util.formatNumber(services.length) + ' services). ' +
                'Narrow the result first &mdash; pick a single system, a service, or enable <em>Privileged only</em>.';
            return false;
        }
        if (!roles.length || !services.length) {
            empty.style.display = ''; empty.textContent = 'No classification data matches the current filters.';
            return false;
        }
        empty.style.display = 'none';

        var cellW = 24, cellH = 18, labelW = 230, headerH = 150;
        var width = labelW + services.length * cellW + 8;
        var height = headerH + roles.length * cellH + 8;
        var svg = d3.select('#tmSankey').attr('width', width).attr('height', height);

        // Column headers (services), rotated.
        var colG = svg.append('g');
        colG.selectAll('text').data(services).join('text')
            .attr('class', 'tm-hm-col')
            .attr('transform', function (d, i) { return 'translate(' + (labelW + i * cellW + cellW / 2) + ',' + (headerH - 6) + ') rotate(-55)'; })
            .text(function (d) { return self.truncate(d, 24); })
            .on('mousemove', function (ev, d) { self.showTip(ev, '<b>' + EOCE.util.escapeHtml(d) + '</b><br>' + EOCE.util.formatNumber(svcMap[d]) + ' role-action path(s)'); })
            .on('mouseleave', function () { self.hideTip(); })
            .style('cursor', 'pointer')
            .on('click', function (ev, d) { ev.stopPropagation(); s.service = d; self.renderToolbar(); self.draw(); });

        // Row labels (roles).
        var rowG = svg.append('g');
        var row = rowG.selectAll('g').data(roles).join('g')
            .attr('transform', function (d, i) { return 'translate(0,' + (headerH + i * cellH) + ')'; });
        row.append('text')
            .attr('class', 'tm-hm-row')
            .attr('x', labelW - 8).attr('y', cellH / 2).attr('dy', '0.35em')
            .text(function (d) { return self.truncate(d.name, 32); })
            .on('mousemove', function (ev, d) {
                self.showTip(ev, '<b>' + EOCE.util.escapeHtml(d.name) + '</b><br>' + EOCE.util.escapeHtml((EOCE.RBAC_SYSTEMS[d.sys] || {}).short || d.sys) +
                    '<br>Highest tier: ' + EOCE.util.escapeHtml(EOCE.tier(EOCE.TIER_ORDER[d.rank] || 'Unclassified').label));
            })
            .on('mouseleave', function () { self.hideTip(); })
            .style('cursor', 'pointer')
            .on('click', function (ev, d) {
                ev.stopPropagation();
                self.setFocusFromNode({ column: 'role', id: 'R:' + d.sys + '|' + d.roleId, name: d.name });
                self._focusMark('R:' + d.sys + '|' + d.roleId);
            });

        // Cells.
        var cellsG = svg.append('g');
        roles.forEach(function (rrole, ri) {
            services.forEach(function (svc, ci) {
                var c = cells[rrole.key + '||' + svc];
                if (!c) return;
                cellsG.append('rect')
                    .attr('class', 'tm-hm-cell')
                    .attr('data-role', rrole.key)
                    .attr('x', labelW + ci * cellW).attr('y', headerH + ri * cellH)
                    .attr('width', cellW - 1).attr('height', cellH - 1).attr('rx', 2)
                    .attr('fill', self.rankColor(c.rank))
                    .style('cursor', 'pointer')
                    .on('mousemove', function (ev) {
                        self.showTip(ev, '<b>' + EOCE.util.escapeHtml(rrole.name) + '</b><br>' + EOCE.util.escapeHtml(svc) +
                            '<br>' + EOCE.util.escapeHtml(EOCE.tier(EOCE.TIER_ORDER[c.rank] || 'Unclassified').label) +
                            '<br>' + EOCE.util.formatNumber(c.count) + ' role action(s)');
                    })
                    .on('mouseleave', function () { self.hideTip(); })
                    .on('click', function (ev) {
                        ev.stopPropagation();
                        self.setFocusFromNode({ column: 'role', id: 'R:' + rrole.sys + '|' + rrole.roleId, name: rrole.name });
                        self._focusMark('R:' + rrole.sys + '|' + rrole.roleId);
                    });
            });
        });

        svg.on('click', function (ev) { if (ev.target.tagName === 'svg') self.clearFocus(); });

        this._clearHighlight = function () { svg.selectAll('.tm-hm-row').classed('sel', false); svg.selectAll('rect.tm-hm-cell').classed('sel', false); };
        this._focusMark = function (id) {
            svg.selectAll('.tm-hm-row').classed('sel', function (d) { return ('R:' + d.sys + '|' + d.roleId) === id; });
            svg.selectAll('rect.tm-hm-cell').classed('sel', function () { return this.getAttribute('data-role') === id.replace(/^R:/, ''); });
        };
        return true;
    },

    highlight: function (node, nodeSel, linkSel) {
        var connected = {};
        connected[node.index] = true;
        function visit(n, dir) {
            var ls = dir === 'down' ? n.sourceLinks : n.targetLinks;
            (ls || []).forEach(function (l) {
                var next = dir === 'down' ? l.target : l.source;
                if (!connected[next.index]) { connected[next.index] = true; visit(next, dir); }
            });
        }
        visit(node, 'down');
        visit(node, 'up');
        nodeSel.classed('dim', function (d) { return !connected[d.index]; });
        linkSel.classed('dim', function (d) { return !(connected[d.source.index] && connected[d.target.index]); });
    },

    focusNode: function (id) {
        if (!this._layoutNodes) return;
        var node = null;
        for (var i = 0; i < this._layoutNodes.length; i++) {
            if (this._layoutNodes[i].id === id) { node = this._layoutNodes[i]; break; }
        }
        if (!node) return;
        this.highlight(node, this._nodeSel, this._linkSel);
        this.setFocusFromNode(node);
        var wrap = document.querySelector('.tm-diagram-wrap');
        if (wrap && wrap.scrollIntoView) wrap.scrollIntoView({ behavior: 'smooth', block: 'start' });
    },

    setFocusFromNode: function (node) {
        this.state.tableFilter = { column: node.column, id: node.id, label: node.name };
        this.renderContrib();
    },

    clearFocus: function () {
        this.state.tableFilter = null;
        if (this._nodeSel) this._nodeSel.classed('dim', false);
        if (this._linkSel) this._linkSel.classed('dim', false);
        if (this._clearHighlight) this._clearHighlight();
        this.renderContrib();
    },

    // ---- Stats -----------------------------------------------------------
    renderStats: function (paths) {
        var roles = {}, services = {}, actions = {};
        var cp = 0, cpRoles = {}, cpActions = {};
        paths.forEach(function (p) {
            roles[p.sys + '|' + p.roleId] = true;
            services[p.sys + '|' + p.service] = true;
            actions[p.sys + '|' + (p.actionType === 'DataAction' ? 'DataAction' : 'Action') + '|' + p.action] = true;
            if (p.tier === 'ControlPlane') {
                cp++;
                cpRoles[p.sys + '|' + p.roleId] = true;
                cpActions[p.sys + '|' + (p.actionType === 'DataAction' ? 'DataAction' : 'Action') + '|' + p.action] = true;
            }
        });
        var stats = [
            { num: Object.keys(roles).length, lbl: 'Roles' },
            { num: Object.keys(services).length, lbl: 'Services' },
            { num: Object.keys(actions).length, lbl: 'Role actions' },
            { num: Object.keys(cpRoles).length, lbl: 'Roles \u2192 Control Plane', danger: true },
            { num: Object.keys(cpActions).length, lbl: 'Control Plane actions', danger: true }
        ];
        document.getElementById('tmStats').innerHTML = stats.map(function (s) {
            return '<div class="tm-stat' + (s.danger ? ' danger' : '') + '"><div class="tm-num">' +
                EOCE.util.formatNumber(s.num) + '</div><div class="tm-lbl">' + s.lbl + '</div></div>';
        }).join('');
    },

    // ---- Contributing actions table -------------------------------------
    contribRows: function () {
        var self = this;
        var rows = this.filteredPaths();
        var tf = this.state.tableFilter;
        if (tf) {
            rows = rows.filter(function (p) { return self.COLUMNS[tf.column].id(p) === tf.id; });
        }
        rows.sort(function (a, b) {
            var ra = self.tierRank(a.tier), rb = self.tierRank(b.tier);
            if (ra !== rb) return ra - rb;
            if (a.role !== b.role) return a.role.toLowerCase() < b.role.toLowerCase() ? -1 : 1;
            return a.action.toLowerCase() < b.action.toLowerCase() ? -1 : 1;
        });
        return rows;
    },

    renderContrib: function () {
        var self = this;
        var rows = this.contribRows();
        var tf = this.state.tableFilter;

        var tag = document.getElementById('tmFocusTag');
        var clear = document.getElementById('tmClearFocus');
        if (tf) {
            tag.style.display = '';
            tag.textContent = self.COLUMNS[tf.column].label + ': ' + tf.label;
            clear.style.display = '';
        } else {
            tag.style.display = 'none';
            clear.style.display = 'none';
        }
        clear.onclick = function () { self.clearFocus(); };

        var html = '<thead><tr>' +
            '<th>Role</th><th class="nowrap">System</th><th>Service</th><th>Role action</th><th class="nowrap">Tier level</th>' +
            '</tr></thead><tbody>';
        if (!rows.length) {
            html += '<tr><td colspan="5"><div class="empty"><div class="big">&#128269;</div>No role actions match.</div></td></tr>';
        } else {
            rows.slice(0, 300).forEach(function (p) {
                html += '<tr class="tm-contrib-row" data-sys="' + EOCE.util.escapeHtml(p.sys) + '" data-action="' + EOCE.util.escapeHtml(p.action) + '" data-action-type="' + EOCE.util.escapeHtml(p.actionType || 'Action') + '">' +
                    '<td><span class="cell-strong">' + EOCE.util.escapeHtml(p.role) + '</span>' +
                    (p.priv ? ' <span class="chip priv">privileged</span>' : '') +
                    (p.docsOnly ? ' <span class="chip docdiff">Learn-only</span>' : '') + '</td>' +
                    '<td class="muted nowrap">' + EOCE.util.escapeHtml((EOCE.RBAC_SYSTEMS[p.sys] || {}).short || p.sys) + '</td>' +
                    '<td class="muted">' + EOCE.util.escapeHtml(p.service) + '</td>' +
                    '<td class="cell-mono">' + EOCE.util.escapeHtml(p.action) + '</td>' +
                    '<td>' + EOCE.util.tierBadge(p.tier) + '</td>' +
                    '</tr>';
            });
        }
        html += '</tbody>';
        var table = document.getElementById('tmContribTable');
        table.innerHTML = html;
        table.querySelectorAll('tbody tr[data-action]').forEach(function (tr) {
            tr.addEventListener('click', function () {
                EOCE.app.go('actions/' + tr.getAttribute('data-sys') + '/' + encodeURIComponent(tr.getAttribute('data-action')) + '/' + tr.getAttribute('data-action-type'));
            });
        });

        var count = document.getElementById('tmContribCount');
        count.textContent = EOCE.util.formatNumber(rows.length) + ' role action' + (rows.length === 1 ? '' : 's') +
            (rows.length > 300 ? ' (showing first 300)' : '');
    },

    // ---- Tooltip / utils -------------------------------------------------
    showTip: function (ev, html) {
        if (!this.tooltip) return;
        this.tooltip.innerHTML = html;
        this.tooltip.style.display = 'block';
        this.tooltip.style.left = (ev.clientX + 14) + 'px';
        this.tooltip.style.top = (ev.clientY + 14) + 'px';
    },
    hideTip: function () { if (this.tooltip) this.tooltip.style.display = 'none'; },

    truncate: function (s, n) {
        s = String(s);
        return s.length > n ? s.slice(0, n - 1) + '\u2026' : s;
    }
};
